spring.application.name=order
server.port=5001
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=order
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

product.service.url=http://localhost:5004
warehouse.service.url=http://localhost:5008
payments.service.url=http://localhost:5003

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
