spring.application.name=payment-service
server.port=5003

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Register + fetch
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Better networking
eureka.instance.prefer-ip-address=true

# Allow external access
server.address=0.0.0.0

