spring.application.name=audit-trail
server.port=5009

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Register + fetch
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Better networking
eureka.instance.prefer-ip-address=true

# Allow external access
server.address=0.0.0.0

# ─────────────────────────────────────────────────────────
# MongoDB — secondary datasource
# ─────────────────────────────────────────────────────────
spring.data.mongodb.uri=mongodb+srv://harshibabu604:harshibabu604@cluster0.uayo1rp.mongodb.net/?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

logging.level.com.harshi_solution=INFO
logging.level.org.springframework.data.mongodb=WARN
logging.level.org.hibernate.SQL=WARN
