version: '3.8'
services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - inventorymate-net

  order-service:
    build: ./order
    container_name: order-service
    ports:
      - "5001:5001"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - inventorymate-net

  party-service:
    build: ./party
    container_name: party-service
    ports:
      - "5002:5002"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - inventorymate-net

  payment-service:
    build: ./payment
    container_name: payment-service
    ports:
      - "5003:5003"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - inventorymate-net

  product-service:
    build: ./product
    container_name: product-service
    ports:
      - "5004:5004"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - inventorymate-net

  transport-service:
    build: ./transport
    container_name: transport-service
    ports:
      - "5006:5006"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - inventorymate-net

  user-service:
    build: ./user
    container_name: user-service
    ports:
      - "5007:5007"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - inventorymate-net

  warehouse-service:
    build: ./warehouse
    container_name: warehouse-service
    ports:
      - "5008:5008"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - inventorymate-net

  frontend:   
    build: ../../inventorymate-frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - inventorymate-net

networks:
  inventorymate-net:
