spring.application.name=eureka_server
server.port=8761

#since it is a server we don't want it to register and also don't want 
#to fetch theinstances details.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false 
