spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=party
spring.datasource.username=postgres
spring.datasource.password=postgres

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka