spring.application.name=party-service
server.port=5002
spring.datasource.url=jdbc:postgresql://192.168.1.40:5432/postgres?currentSchema=party
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
# eureka.client.register-with-eureka=true
# eureka.client.fetch-registry=true

# Eureka location (container name)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# Register + fetch
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Better networking
eureka.instance.prefer-ip-address=true

# Allow external access
server.address=0.0.0.0

