-- Set search path to user schema
SET search_path TO "user";

-- The users table will be created by Hibernate (ddl-auto=update) before this runs
-- But to be safe we create it here too so the insert doesn't fail
-- Hibernate will skip creation if table already exists

CREATE TABLE IF NOT EXISTS "user".user_register
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_register_pkey PRIMARY KEY (id),
    CONSTRAINT ukagthxtxpihn020he0qlriosa3 UNIQUE (username),
    CONSTRAINT user_register_role_check CHECK (role::text = ANY (ARRAY['ROLE_ADMIN'::character varying, 'ROLE_REPS'::character varying, 'ROLE_VIEW'::character varying]::text[]))
)

-- Insert admin user only if not already present
-- Password is BCrypt encoded 'Password@123'
INSERT INTO "user".user_register(
	id, password, role, username)
	VALUES (1,'$2a$10$lNXU7k.BMotpg1JCv/sMyOw6Dp22Nfu7qIF.SvoG.49Gx1XoJNOO2', 'ROLE_ADMIN', 'admin')
ON CONFLICT (username) DO NOTHING;